[package]
name = "subset-macro"
version = "0.1.0"
authors = ["Cassaundra Smith <cass@cassaundra.io>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
proc-macro-error = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
